import jsPDF from "jspdf";
import QRCode from "qrcode";
import type { TreeProofRecord } from "@/types";

export async function generateCertificatePDF(record: TreeProofRecord) {
  const pdf = new jsPDF("p", "mm", "a4");

  const qrImage = await QRCode.toDataURL(record.qrData);


  // Background
  pdf.setFillColor(248, 250, 252);
  pdf.rect(0, 0, 210, 297, "F");

  // Outer Border
  pdf.setDrawColor(22, 163, 74);
  pdf.setLineWidth(1.2);
  pdf.rect(10, 10, 190, 277);

  // Inner Border
  pdf.setDrawColor(187, 247, 208);
  pdf.setLineWidth(0.5);
  pdf.rect(14, 14, 182, 269);

  // Header
  pdf.setTextColor(22, 163, 74);

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(28);
  pdf.text("GreenDot Chain", 20, 28);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.setTextColor(100);
  pdf.text(
    "IPL 2026 Blockchain Sustainability Verification",
    20,
    36
  );

  // Green Line
  pdf.setDrawColor(22, 163, 74);
  pdf.setLineWidth(0.8);
  pdf.line(20, 44, 190, 44);

  // Certificate Title
  pdf.setTextColor(15, 23, 42);

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(24);
  pdf.text("CERTIFICATE OF AUTHENTICITY", 20, 62);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.setTextColor(90);

  pdf.text(
    "This certificate confirms that the following tree plantation proof",
    20,
    72
  );

  pdf.text(
    "has been securely registered and verified on blockchain.",
    20,
    79
  );


  // Details Card
  pdf.setFillColor(240, 253, 244);
  pdf.roundedRect(20, 90, 170, 92, 4, 4, "F");

  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(22, 163, 74);
  pdf.setFontSize(14);

  pdf.text("Plantation Proof Details", 28, 102);

  const details = [
    ["Proof ID", record.id],
    ["Match", record.matchName],
    ["Over", record.overNumber],
    ["Bowler", record.bowlerName],
    ["Trees Allocated", String(record.treesCount)],
    ["Location", record.location],
    ["Plantation Date", record.plantationDate],
    ["Verifier", record.verifierName],
    ["Image File", record.imageName],
    ["Status", record.status],
  ];

  let y = 115;

  details.forEach(([label, value]) => {
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(10);
    pdf.setTextColor(22, 163, 74);

    pdf.text(`${label}:`, 28, y);

    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(55);

    pdf.text(String(value), 78, y);

    y += 7;
  });


  // Hash Section - Clear Version
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(13);
  pdf.setTextColor(15, 23, 42);
  pdf.text("Blockchain Verification Hashes", 20, 196);

  // Image Hash Box
  pdf.setFillColor(255, 255, 255);
  pdf.roundedRect(20, 202, 112, 30, 3, 3, "F");

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(9);
  pdf.setTextColor(22, 163, 74);
  pdf.text("Image SHA256 Hash", 25, 211);

  pdf.setFont("courier", "normal");
  pdf.setFontSize(7.2);
  pdf.setTextColor(45, 45, 45);

  const imageHashLines = pdf.splitTextToSize(record.imageHash, 100);
  pdf.text(imageHashLines, 25, 219);

  // Transaction Hash Box
  pdf.setFillColor(255, 255, 255);
  pdf.roundedRect(20, 238, 112, 30, 3, 3, "F");

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(9);
  pdf.setTextColor(22, 163, 74);
  pdf.text("Transaction Hash", 25, 247);

  pdf.setFont("courier", "normal");
  pdf.setFontSize(7.2);
  pdf.setTextColor(45, 45, 45);

  const txHashLines = pdf.splitTextToSize(record.txHash, 100);
  pdf.text(txHashLines, 25, 255);

  // QR Code - Bigger Version
  pdf.setFillColor(255, 255, 255);
  pdf.roundedRect(142, 202, 42, 58, 4, 4, "F");

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(9);
  pdf.setTextColor(22, 163, 74);
  pdf.text("Verification QR", 150, 211);

  pdf.addImage(qrImage, "PNG", 148, 216, 30, 30);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(7);
  pdf.setTextColor(90);
  pdf.text("Scan to verify proof", 149, 252);


  // Footer - Fixed Position
  pdf.setDrawColor(200);
  pdf.line(20, 270, 190, 270);

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(8.5);
  pdf.setTextColor(80);
  pdf.text("Authorized Blockchain Verification", 20, 276);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(7.5);
  pdf.setTextColor(90);

  pdf.text(`Issued: ${new Date(record.issuedAt).toLocaleString()}`, 20, 282);

  pdf.text(
    "Generated by GreenDot Chain Verification Platform",
    130,
    282
  );

  // Save
  pdf.save(`${record.id}-certificate.pdf`);
}